id: Mission_Control_Application_Shield_keyword
info:
  name: Mission-Control-Application-Shield_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Mission-Control-Application-Shield"
        words:
          - "alt=\"mission control application shield"
        condition: and