id: Prometheus_Node_Exporter_keyword
info:
  name: Prometheus Node Exporter_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Prometheus Node Exporter"
        words:
          - "Prometheus Node Exporter"
        condition: and