id: SAP_Web_Application_Server_keyword
info:
  name: SAP-Web-Application-Server_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "SAP-Web-Application-Server"
        words:
          - "name=\"sap-login-xsrf"
        condition: and