id: DAS_Security_DAS_WEB_Application_Firewall_keyword
info:
  name: DAS-Security-DAS-WEB-Application-Firewall_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "DAS-Security-DAS-WEB-Application-Firewall"
        words:
          - "<img id=\"company_logo\" src=\"images/waf.company.png"
        condition: and