id: Oracle_Application_Server_keyword
info:
  name: Oracle-Application-Server_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Oracle-Application-Server"
        words:
          - "oracle http server</font></font></b></h1>"
        condition: and