id: Enhydra_Application_Server_keyword
info:
  name: Enhydra-Application-Server_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Enhydra-Application-Server"
        words:
          - "enhydra"
        condition: and
      - type: word
        part: header
        name: "Enhydra-Application-Server"
        words:
          - "Enhydra"
        condition: and