id: Tongtech_application_server_TongWeb_keyword
info:
  name: Tongtech-application-server-TongWeb_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Tongtech-application-server-TongWeb"
        words:
          - "tongweb server"
        condition: and