id: Advantech_Module_Web_Configuration_keyword
info:
  name: Advantech Module Web Configuration_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Advantech Module Web Configuration"
        words:
          - "Advantech Module Web Configuration"
        condition: and