id: ChinaTelecomEquipmentWEBConfigurationSystem_keyword
info:
  name: ChinaTelecomEquipmentWEBConfigurationSystem_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "ChinaTelecomEquipmentWEBConfigurationSystem"
        words:
          - "设备web配置</font"
        condition: and