id: ManageEngine_Applications_Manager_keyword_1_1
info:
  name: ManageEngine Applications Manager_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "ManageEngine Applications Manager"
        words:
          - "ManageEngine Applications Manager"
        condition: and