id: VRV_Desktop_Application_System_keyword
info:
  name: VRV-Desktop-Application-System_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "VRV-Desktop-Application-System"
        words:
          - "<span id=\"lblvalidcompany\" class=\"validcompany\">vrv"
          - "var vver = $('#hidverify'.val(;"
        condition: and