id: Tomcat_Manager_Application_keyword
info:
  name: Tomcat-Manager-Application_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Tomcat-Manager-Application"
        words:
          - "tomcat manager application"
        condition: and