id: Venustech_TianQing_Application_Security_Gateway_keyword
info:
  name: Venustech-TianQing-Application-Security-Gateway_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Venustech-TianQing-Application-Security-Gateway"
        words:
          - "v2/global/vendor/modernizr/modernizr.js"
          - "天清web应用安全网关"
        condition: and