id: CETHIK_Reader_Configuration_System_keyword
info:
  name: CETHIK-Reader-Configuration-System_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "CETHIK-Reader-Configuration-System"
        words:
          - "if (suser == \"admin\" && spass == \"cetc52\" {"
          - "rfid/content/superuser"
        condition: and