id: Prometheus_Server_keyword
info:
  name: Prometheus Server_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Prometheus Server"
        words:
          - "<title>Prometheus Time Series Collection and Processing Server"