id: Sangfor_Application_Delivery_keyword
info:
  name: Sangfor-Application-Delivery_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Sangfor-Application-Delivery"
        words:
          - "default_target=\"/cgi-bin/login.cgi?action=log&fro=self"
          - "var check_login_key"
          - "/static/es5_shim/es5-sham.js"
        condition: and