id: SAP_Web_Application_Server_keyword_1
info:
  name: SAP-Web-Application-Server_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "SAP-Web-Application-Server"
        words:
          - "sap-usercontext"
          - "server: sap j2ee engine"
        condition: and