id: Outlook_Web_Application_faviconhash
info:
  name: Outlook Web Application_faviconhash
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}//favicon.ico"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: dsl
        name: "Outlook Web Application"
        dsl:
          - "mmh3(base64_py(body)) == \"1768726119\""
          - "mmh3(base64_py(body)) == \"1356662359\""
        condition: or