id: Horde_Application_Framework_keyword
info:
  name: Horde-Application-Framework_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Horde-Application-Framework"
        words:
          - "Powered by Horde"
        condition: and
      - type: word
        part: body
        name: "Horde-Application-Framework"
        words:
          - "<img src=\"/themes/default/graphics/horde-power1.png"
        condition: and