id: Horde_Application_Framework_keyword_1
info:
  name: Horde-Application-Framework_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Horde-Application-Framework"
        words:
          - "horde_secret_key"
        condition: and