id: WebHare_Application_Portal_keyword
info:
  name: WebHare Application Portal_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "WebHare Application Portal"
        words:
          - "WebHare Application Portal"
        condition: and