id: Razuna_Application_Server_keyword
info:
  name: Razuna Application Server_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Razuna Application Server"
        words:
          - "Razuna Application Server"
        condition: and