id: IBM_WebSphere_Application_keyword
info:
  name: IBM WebSphere Application_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "IBM WebSphere Application"
        words:
          - "IBM WebSphere Application"
        condition: and