id: Proxmox_Virtual_Environment_REST_API_keyword
info:
  name: Proxmox Virtual Environment REST API_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: header
        name: "Proxmox Virtual Environment REST API"
        words:
          - "Proxmox Virtual Environment REST API"
        condition: and