id: Sangfor_Application_Performance_Management_keyword
info:
  name: Sangfor-Application-Performance-Management_keyword
  author: GLAN
  severity: info
  tags: tech
http:
  - method: GET
    path:
      - "{{RootURL}}{{Path}}/"
    cookie-reuse: true
    matchers-condition: or
    redirects: true
    matchers:
      - type: word
        part: body
        name: "Sangfor-Application-Performance-Management"
        words:
          - "help=\"版本信息:<br/>apm-"
        condition: and